# syntax=docker/dockerfile:1
# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Base image built from the original b7 Dockerfile:
ARG BASE_IMAGE=intel/llm-scaler-omni:0.1.0-b7
ARG PYTHON_VERSION=3.12

FROM ${BASE_IMAGE}

ARG https_proxy
ARG http_proxy
ARG PYTHON_VERSION

ENV LD_LIBRARY_PATH="/usr/local/lib:/usr/local/lib/python${PYTHON_VERSION}/dist-packages/torch/lib:${LD_LIBRARY_PATH}"

COPY ./patches/extention_comfyui_wanvideowrapper.patch /tmp/
COPY ./patches/comfyui-layerstyle_advance-add-intel-xpu-support-for-joy-caption-beta1.patch /tmp/
COPY ./patches/art-venture-resize-mask-to-match-image-spatial-size.patch /tmp
COPY ./patches/extention_comfyui_florence2.patch /tmp/
COPY ./patches/extension_comfyui_segment_anything_2.patch /tmp/
COPY ./patches/extension_comfyui_reactor.patch /tmp/
COPY ./patches/extension_comfyui_rmbg.patch /tmp/

# Add custom node
RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf ComfyUI-WanVideoWrapper && \
    git clone --depth 1 https://github.com/kijai/ComfyUI-WanVideoWrapper.git && \
    cd ComfyUI-WanVideoWrapper && \
    git fetch --depth 1 origin e091c4a77425d6a4a7f90ab30c513d24f8cb91cf && \
    git checkout e091c4a77425d6a4a7f90ab30c513d24f8cb91cf && \
    git apply /tmp/extention_comfyui_wanvideowrapper.patch && \
    pip install -r requirements.txt && \
    rm -f /tmp/extention_comfyui_wanvideowrapper.patch && \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf ComfyUI_LayerStyle_Advance && \
    git clone --depth 1 https://github.com/chflame163/ComfyUI_LayerStyle_Advance.git && \
    cd ComfyUI_LayerStyle_Advance && \
    git fetch --depth 1 orgin 7b678b401a38307a4a7e99ef6630bd48f9cecedb && \
    git checkout 7b678b401a38307a4a7e99ef6630bd48f9cecedb && \
    git apply /tmp/comfyui-layerstyle_advance-add-intel-xpu-support-for-joy-caption-beta1.patch && \
    pip install segment_anything wget blend_modes && \
    pip install -r requirements.txt && \
    rm -rf /tmp/comfyui-layerstyle_advance-add-intel-xpu-support-for-joy-caption-beta1.patch && \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf comfyui-mixlab-nodes && \
    git clone https://github.com/MixLabPro/comfyui-mixlab-nodes.git && \
    cd comfyui-mixlab-nodes && \
    git fetch --depth 1 origin 32b22c39cbe13b46df29ef1b6ab088c2eb4389d2 && \
    git checkout 32b22c39cbe13b46df29ef1b6ab088c2eb4389d2 && \
    pip install -r requirements.txt && \
    pip install --ignore-installed cryptography && \
    pip install pyOpenSSL && \
    pip install setuptools==70.2.0 && \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf comfyui-art-venture && \
    git clone --depth 1 https://github.com/sipherxyz/comfyui-art-venture && \
    cd comfyui-art-venture && \
    git fetch --depth 1 origin 210dc072b1f103f91be18a33bdeb13ab315aaae5 && \
    git checkout 210dc072b1f103f91be18a33bdeb13ab315aaae5 && \
    git apply /tmp/art-venture-resize-mask-to-match-image-spatial-size.patch && \
    pip install -r requirements.txt && \
    rm -rf /tmp/art-venture-resize-mask-to-match-image-spatial-size.patch

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf comfyui-florence2 && \
    git clone --depth 1 https://github.com/kijai/ComfyUI-Florence2.git comfyui-florence2 && \
    cd comfyui-florence2 && \
    git fetch --depth 1 origin 9ece3de914214c5f581d725167bc9d0eeb0d1120 && \
    git checkout 9ece3de914214c5f581d725167bc9d0eeb0d1120 && \
    git apply /tmp/extention_comfyui_florence2.patch && \
    pip install -r requirements.txt && \
    rm -f /tmp/extention_comfyui_florence2.patch

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf comfyui_layerstyle && \
    git clone --depth 1 https://github.com/chflame163/ComfyUI_LayerStyle.git comfyui_layerstyle && \
    cd comfyui_layerstyle && \
    git fetch --depth 1 origin d94bef1ee5ed3656f5ff1bb2830a4ffd94f40935 && \
    git checkout d94bef1ee5ed3656f5ff1bb2830a4ffd94f40935 && \
    pip install -r requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf comfyui-segment-anything-2 && \
    git clone --depth 1 https://github.com/kijai/ComfyUI-segment-anything-2.git comfyui-segment-anything-2 && \
    cd comfyui-segment-anything-2 && \
    git fetch --depth 1 origin 0c35fff5f382803e2310103357b5e985f5437f32 && \
    git checkout 0c35fff5f382803e2310103357b5e985f5437f32 && \
    git apply /tmp/extension_comfyui_segment_anything_2.patch && \
    rm -f /tmp/extension_comfyui_segment_anything_2.patch

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf extension_comfyui_reactor && \
    git clone --depth 1 https://github.com/Gourieff/ComfyUI-ReActor.git comfyui-reactor && \
    cd comfyui-reactor && \
    git fetch --depth 1 origin 6ad6b35a4df250d14cb2abf0808c9ffedf59f747 && \
    git checkout 6ad6b35a4df250d14cb2abf0808c9ffedf59f747 && \
    git apply /tmp/extension_comfyui_reactor.patch && \
    python install.py && \
    rm -f /tmp/extension_comfyui_reactor.patch

RUN --mount=type=cache,target=/root/.cache/pip \
    cd /llm/ComfyUI/custom_nodes && \
    rm -rf ComfyUI-RMBG && \
    git clone --depth 1 https://github.com/1038lab/ComfyUI-RMBG.git && \
    cd ComfyUI-RMBG && \
    git fetch --depth 1 origin d7402513f23f58db7d56754b02a4f51a148b4941 && \
    git checkout d7402513f23f58db7d56754b02a4f51a148b4941 && \
    git apply /tmp/extension_comfyui_rmbg.patch && \
    pip install -r requirements.txt && \
    rm -f /tmp/extension_comfyui_rmbg.patch

WORKDIR /llm/entrypoints
