#!/usr/bin/env bash
# Pre-fetch the Qwen3.6 tokenizer (the fork's Qwen/Qwen3.6-35B-A3B-FC config
# points model_name at "Qwen/Qwen3.6-35B-A3B" which does NOT exist on HF — we
# pass --local-model-path <unsloth tokenizer> instead) and write RUN_CONFIG.sh.
#
# Runs INSIDE the container.
set -euo pipefail

VENV="${VENV:-/opt/venv}"
WORKDIR="${WORKDIR:-/workspace/bfcl_kit/workspace_xpu}"
PORT="${PORT:-9010}"
# Reuse the already-downloaded unsloth tokenizer snapshot if present; else fetch.
TOK_DIR="${TOK_DIR:-}"

source "$VENV/bin/activate"
mkdir -p "$WORKDIR"

if [[ -z "$TOK_DIR" ]]; then
  # find an existing unsloth Qwen3.6 tokenizer snapshot
  TOK_DIR=$(ls -d /root/.cache/huggingface/hub/models--unsloth--Qwen3.6-35B-A3B/snapshots/*/ 2>/dev/null | head -1 || true)
fi
if [[ -z "$TOK_DIR" || ! -f "$TOK_DIR/tokenizer.json" ]]; then
  echo "Fetching unsloth/Qwen3.6-35B-A3B tokenizer files..."
  python3 - <<'PY'
from huggingface_hub import snapshot_download
d = snapshot_download(
    "unsloth/Qwen3.6-35B-A3B",
    allow_patterns=["tokenizer*","*.json","merges.txt","vocab.json"],
)
print("DOWNLOADED_TO", d)
PY
  TOK_DIR=$(ls -d /root/.cache/huggingface/hub/models--unsloth--Qwen3.6-35B-A3B/snapshots/*/ 2>/dev/null | head -1)
fi
echo "Tokenizer dir: $TOK_DIR"
[ -f "$TOK_DIR/tokenizer.json" ] || { echo "ERROR: tokenizer.json missing in $TOK_DIR"; exit 1; }

cat > "$WORKDIR/RUN_CONFIG.sh" <<EOF
# Auto-generated by 03_prepare_workspace.sh
export TOK_DIR="$TOK_DIR"
export REMOTE_OPENAI_BASE_URL="http://127.0.0.1:$PORT/v1"
export REMOTE_OPENAI_API_KEY="sk-dummy"
export LOCAL_SERVER_ENDPOINT="127.0.0.1"
export LOCAL_SERVER_PORT="$PORT"
export BFCL_PROJECT_ROOT="$WORKDIR"
EOF
echo "Wrote $WORKDIR/RUN_CONFIG.sh:"
cat "$WORKDIR/RUN_CONFIG.sh"
